name: CD

on:
  push:
    branches:
      - master

  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle Build
        run: gradle jsBrowserDistribution

      - name: Save sample
        uses: actions/upload-artifact@v3
        with:
          path: src/jsMain/resources

      - name: Publish to Pages
        uses: actions/checkout@v3
        with:
          ref: build

      - uses: actions/download-artifact@v3

      - name: Copy files to /
        run: cp -r artifact/* . && rm -Rf artifact/*

      - name: Config git
        run: git config user.email "github-actions@github.com" && git config user.name "CD Bot"

      - name: Add changes
        run: git add .

      - name: List files
        run:
          \ls -la
          \git status

      - name: Try to commit changes
        run: git commit -m "Update build."
        continue-on-error: true

      - name: Publish changes
        run: git push
        if: ${{ success() }}
