name: Data

on:
  schedule:
    - cron: 0 0 * * 1

  workflow_dispatch:

jobs:
  data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: api

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Run gradle
        run: ./gradlew run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit result
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy data.
          file_pattern: "*result.json"
